# Generated by Django 4.2.3 on 2023-07-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='subtitle',
        ),
    ]
