# Generated by Django 4.2.3 on 2023-07-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialplatform_alter_facts_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
