# Generated by Django 4.2.3 on 2023-07-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_abouts_alter_contact_call_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts',
            name='title_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Abouts/'),
        ),
    ]
