# Generated by Django 4.2.3 on 2023-07-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='tittle_description',
            new_name='title_description',
        ),
    ]
