# Generated by Django 4.2.3 on 2023-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_tittle_description_services_title_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='skiill_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
