# Generated by Django 4.2.3 on 2023-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_skiill_description_remove_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatform',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
