# Generated by Django 4.2.3 on 2023-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_title_services_s1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='s1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s1d',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s2d',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s3d',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s4d',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s5d',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='services',
            name='s6d',
        ),
        migrations.AddField(
            model_name='services',
            name='title_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
