# Generated by Django 4.2.3 on 2023-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_services_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
