# Generated by Django 4.2.3 on 2023-07-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_hero_hero_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_img',
        ),
    ]
