# Generated by Django 4.2.3 on 2023-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_hero_hero_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='photo',
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
