# Generated by Django 4.2.3 on 2023-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_services_photo_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('category', models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Card', 'Card')], max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
