# Generated by Django 4.2.3 on 2023-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_education_degree_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
