# Generated by Django 4.2.3 on 2023-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
