# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
