# Generated by Django 4.2.3 on 2023-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cSkill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='skilldescrption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
