# Generated by Django 4.2.3 on 2023-08-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_delete_cskill_remove_skill_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skilldescrption',
            new_name='skilldescription',
        ),
    ]
