# Generated by Django 4.2.3 on 2023-08-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_skilldescrption_skill_skilldescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skiill_description',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
